[package]
name = "dms-desktop"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
default-run = "dms-desktop"

[lib]
name = "dms_desktop"
path = "src/lib.rs"

[[bin]]
name = "dms-desktop"
path = "src/main.rs"

[build-dependencies]
tauri-build.workspace = true

[dependencies]
chrono.workspace = true
dms-core = { path = "../dms-core" }
pulldown-cmark.workspace = true
quick-xml.workspace = true
serde.workspace = true
serde_json.workspace = true
tauri.workspace = true
tauri-plugin-deep-link.workspace = true
tauri-plugin-dialog.workspace = true
tauri-plugin-single-instance.workspace = true
tempfile.workspace = true
uuid.workspace = true
zip.workspace = true

[target.'cfg(windows)'.dependencies]
webview2-com.workspace = true
windows.workspace = true

[target.'cfg(target_os = "macos")'.dependencies]
block2.workspace = true
objc2-foundation.workspace = true
objc2-web-kit.workspace = true

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
