[package]
name = "dms-desktop"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
default-run = "dms-desktop"

[lib]
name = "dms_desktop"
path = "src/lib.rs"

[[bin]]
name = "dms-desktop"
path = "src/main.rs"

[build-dependencies]
tauri-build.workspace = true

[dependencies]
dms-core = { path = "../dms-core" }
serde.workspace = true
serde_json.workspace = true
tauri.workspace = true
uuid.workspace = true

[dev-dependencies]
tempfile.workspace = true

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
