[package]
name = "dms-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "dms"
path = "src/main.rs"

[dependencies]
clap.workspace = true
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true
dms-core = { path = "../dms-core" }

[dev-dependencies]
serde_json.workspace = true
tempfile.workspace = true
